table_name: product_state_orders
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: brazilian
schema: null
sql: "SELECT \n    pct.product_category_name_english AS product_category,\n    c.customer_state,\n\
  \    COUNT(*) AS order_count\nFROM orders o\nJOIN order_items oi ON o.order_id =\
  \ oi.order_id\nJOIN products p ON oi.product_id = p.product_id\nJOIN product_category_translation\
  \ pct ON p.product_category_name = pct.product_category_name\nJOIN customers c ON\
  \ o.customer_id = c.customer_id\nWHERE o.order_status = 'delivered'\nGROUP BY pct.product_category_name_english,\
  \ c.customer_state\nORDER BY order_count DESC;\n"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: d1e1e016-4b08-45be-8c38-fcd95f523c95
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: order_count
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: product_category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: customer_state
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: 01bb104e-81b6-4ea9-bd17-b7a0e4ee9dd1
